config/routes.rb
Rails.application.routes.draw do
  get 'intermediate/transition'
  get 'prehome/index'
  get 'payments/new'
  get 'checkouts/create'
  devise_for :users
  root to: "prehome#index"

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :shops, only: [:index, :new, :show, :create, :destroy]

  resources :orders, only: [:index, :show] do
    resources :payments, only: [:new]
  end
  resources :products do
    member do
      post 'add_to_cart', to: 'carts#add_item'
    end
  end

  resource :cart, only: [:show] do
    post 'add_item/:product_id', to: 'carts#add_item', as: 'add_item'
    delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
  end

  post 'checkout/create', to: 'checkouts#create', as: 'checkout_create'

  get 'prehome', to: 'prehome#index', as: 'prehome'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_order, only: [:add_item, :show, :remove_item]

  def add_item
    product = Product.find(params[:product_id])
    @cart_item = @order.order_items.find_or_initialize_by(product: product)

    @cart_item.unit_price = product.price
    @cart_item.quantity += 1 unless @cart_item.new_record?

    if @cart_item.save
      redirect_to shops_path, notice: 'Product was successfully added to your cart.'
    else
      redirect_to product_path(product), alert: 'There was a problem adding the product to your cart.'
    end
  end

  def remove_item
    product = Product.find(params[:product_id])
    @cart_item = @order.order_items.find_by(product: product)

    if @cart_item
      @cart_item.destroy
      redirect_to cart_path, notice: 'Product was successfully removed from your cart.'
    else
      redirect_to cart_path, alert: 'Product not found in your cart.'
    end
  end

  def show
    @order_items = @order.order_items
  end

  private

  def set_order
    @order = Order.find_or_initialize_by(user: current_user, status: 'cart')
    if @order.new_record?
      @order.total_price = 0
      @order.save
    end
  end
end

app/views/carts/add.html.erb
<h1>Carts#add</h1>
<p>Find me in app/views/carts/add.html.erb</p>

app/views/carts/remove.html.erb
<h1>Carts#remove</h1>
<p>Find me in app/views/carts/remove.html.erb</p>

app/views/carts/show.html.erb
<h1 class="p-5 text-white">My Cart</h1>
<% if @order_items.any? %>
  <table class="table mb-5">
    <thead>
      <tr>
        <th class="py-2">Product</th>
        <th class="py-2">Quantity</th>
        <th class="py-2">Unit Price</th>
        <th class="py-2">Total</th>
        <th class="py-2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |item| %>
        <tr>
          <td class="py-2"><%= item.product.name %></td>
          <td class="py-2"><%= item.quantity %></td>
          <td class="py-2"><%= number_to_currency(item.unit_price) %></td>
          <td class="py-2"><%= number_to_currency(item.unit_price * item.quantity) %></td>
          <td class="py-2">
            <%= button_to 'Remove', remove_item_cart_path(item.product), method: :delete, class: 'rounded-full m-0 text-white' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h2 class="mb-4 p-3 text-white">Total <%= number_to_currency(@order_items.sum { |item| item.unit_price * item.quantity }) %> dollars</h2>
  <div class="flex justify-start m-5">
    <%= button_to 'Checkout', checkout_create_path, method: :post, class: 'rounded-full text-white' %>
  </div>
<% else %>
  <p class="my-4 p-5 text-white">Your cart is empty.</p>
<% end %>


<style>

button.rounded-full.text-white {
  padding: 0.370rem;
  background-color: #0000FF;
}

button.rounded-full.text-white:hover {
  padding: 0.370rem;
   background-color: #060663;
}

button.rounded-full.m-0.text-white {
  padding: 0.370rem;
  background-color: #e50915;
}

button.rounded-full.m-0.text-white:hover {
  padding: 0.370rem;
  background-color: #e50600;
}

</style>