config/routes.rb
Rails.application.routes.draw do
  get 'intermediate/transition'
  get 'prehome/index'
  get 'payments/new'
  get 'checkouts/create'
  devise_for :users
  root to: "prehome#index"

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :shops, only: [:index, :new, :show, :create, :destroy]

  resources :orders, only: [:index, :show] do
    resources :payments, only: [:new]
  end
  resources :products do
    member do
      post 'add_to_cart', to: 'carts#add_item'
    end
  end

  resource :cart, only: [:show] do
    post 'add_item/:product_id', to: 'carts#add_item', as: 'add_item'
    delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
  end

  post 'checkout/create', to: 'checkouts#create', as: 'checkout_create'

  get 'prehome', to: 'prehome#index', as: 'prehome'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      # Recherche de produits par nom
      @products = Product.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @products = Product.all
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    else
      redirect_to products_url, alert: 'Failed to destroy the product. Please try again.'
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :image_url)
  end
end

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: 'btn btn-secondary' %>

app/views/products/index.html.erb
<h1 class="text-white">Products</h1>

<%# <%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %> %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: 'btn btn-secondary' %>

app/views/products/show.html.erb
<div id="container", class="product-details-container mx-auto max-w-2xl my-10 p-5 border rounded-lg shadow-lg">
  <div class="text-center mb-5">
    <%= image_tag @product.image_url, alt: @product.name, class: 'product-image mx-auto' %>
  </div>
  <h1 class="text-2xl mb-3 text-black"><%= @product.name %></h1>
  <p class="mb-4 text-black"><strong>Description -</strong> <%= @product.description %></p>
  <p class="mb-4 text-black font-bold"> <%= number_to_currency(@product.price) %>$</p>
  <p class="mb-4 text-black"><strong>Stock -</strong> <%= @product.stock %></p>
  <div class="product-btn flex justify-center space-x-4 mt-5">
    <%= link_to 'Back', shops_path, class: 'btn rounded-full text-black' %>
    <%= button_to 'Add to Cart', add_item_cart_path(@product), method: :post, class: 'rounded-full text-white' %>
  </div>
</div>

<style>

  h1 {
    font-family: 'Starjout', sans-serif;
  }

  #container {
    background-color: #ffeb02;
  }

  button.rounded-full.text-white {
    padding: 0.400rem;
    background-color: #0000FF;
  }

  button.rounded-full.text-white:hover {
    padding: 0.400rem;
    background-color: #060663;
  }

  .product-details-container {
    max-width: 32rem;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    background-color: #1e2836;
  }

  .product-image {
    max-width: 100%;
    height: auto;
  }

  .product-btn {
    display: flex;
    justify-content: center;
    gap: 1rem;
  }

  .product-btn .btn {
    padding: 0.5rem 1rem;
    border-radius: 0.25rem;
  }
</style>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>